import { DemoService } from '../services/demo-service.js';
import { icon } from '../utils/icons.js';
import { escapeHtml, formatDate, formatCurrency } from '../utils/format.js';
import { renderKanban } from './kanban-view.js';
import { renderToolkit } from './toolkit-view.js';

const tabs=[['summary','Resumen'],['innovation','Canvases'],['kanban','Kanban'],['timeline','Cronograma'],['documents','Documentos'],['team','Equipo'],['finance','Finanzas'],['hours','Horas'],['activity','Actividad']];
export function renderProject(container,{projectId,tab='summary'}){
  const p=DemoService.getProject(projectId);
  if(!p){container.innerHTML='<div class="empty-state"><h3>Proyecto no encontrado</h3></div>';return;}
  container.innerHTML=`<section class="page"><div class="content-grid-project"><div><article class="project-hero"><div class="project-hero-top"><div class="project-hero-logo">${p.logo?`<img src="${p.logo}" alt="">`:escapeHtml(p.name.slice(0,2).toUpperCase())}</div><div class="project-hero-title"><a class="panel-link" href="#/w/${p.workspaceId}/projects">${icon('arrowLeft')} Volver a proyectos</a><h1>${escapeHtml(p.name)}</h1><p>${escapeHtml(p.tagline)}</p></div><span class="badge badge-blue">${p.progress}% completado</span></div><nav class="project-tabs">${tabs.map(([key,label])=>`<a class="project-tab ${tab===key?'active':''}" href="#/w/${p.workspaceId}/p/${p.id}/${key}">${label}</a>`).join('')}</nav></article><div id="project-tab-content"></div></div><aside class="project-aside"><h2>Informacion del proyecto</h2><div class="info-list"><div class="info-row"><span>Estado</span><strong>En desarrollo</strong></div><div class="info-row"><span>Cliente</span><strong>${escapeHtml(p.client)}</strong></div><div class="info-row"><span>Responsable</span><strong>${escapeHtml(p.owner)}</strong></div><div class="info-row"><span>Prioridad</span><strong>${escapeHtml(p.priority)}</strong></div><div class="info-row"><span>Inicio</span><strong>${formatDate(p.startDate)}</strong></div><div class="info-row"><span>Entrega</span><strong>${formatDate(p.dueDate)}</strong></div><div class="info-row"><span>Presupuesto</span><strong>${formatCurrency(p.budget)}</strong></div></div><button class="button button-primary drive-button" id="drive-demo">${icon('external')} Abrir en Drive</button></aside></div></section>`;
  const slot=document.querySelector('#project-tab-content');
  if(tab==='kanban') renderKanban(slot,p.workspaceId,p.id,true);
  else if(tab==='innovation') renderToolkit(slot,p.workspaceId,p.id,true);
  else renderTab(slot,p,tab);
  document.querySelector('#drive-demo')?.addEventListener('click',()=>alert('La integracion real con Google Drive se implementara en la Entrega 3.'));
}
function renderTab(slot,p,tab){
  if(tab!=='summary'){slot.innerHTML=`<div class="empty-state" style="margin-top:18px"><div class="empty-state-icon">${icon('layers')}</div><h3>${tabs.find(t=>t[0]===tab)?.[1]||'Modulo'}</h3><p>La estructura visual esta preparada. La funcionalidad real se conectara en su entrega correspondiente.</p></div>`;return;}
  slot.innerHTML=`<div class="project-summary-grid"><article class="panel"><div class="panel-header"><div><h2>Objetivo y alcance</h2><p>Resumen ejecutivo del proyecto.</p></div></div><div class="panel-body"><p style="margin:0;color:var(--text-muted)">${escapeHtml(p.description)}</p><div style="margin-top:18px"><div class="progress-head"><span>Avance general</span><strong>${p.progress}%</strong></div><div class="progress-track"><div class="progress-bar" style="width:${p.progress}%"></div></div></div></div></article><article class="panel"><div class="panel-header"><div><h2>Salud del proyecto</h2><p>Indicadores demostrativos.</p></div></div><div class="panel-body"><div class="info-list"><div class="info-row"><span>Tiempo</span><strong>En rango</strong></div><div class="info-row"><span>Costo</span><strong>${formatCurrency(p.cost)} ejecutado</strong></div><div class="info-row"><span>Alcance</span><strong>Estable</strong></div><div class="info-row"><span>Horas</span><strong>${p.hours} h</strong></div></div></div></article><article class="panel"><div class="panel-header"><div><h2>Proximos hitos</h2></div></div><div class="panel-body task-list"><div class="task-row"><span class="task-check"></span><span class="list-copy"><strong>Validar entregable principal</strong><small>Responsable: ${escapeHtml(p.owner)}</small></span></div><div class="task-row"><span class="task-check"></span><span class="list-copy"><strong>Actualizar documentacion</strong><small>Antes de ${formatDate(p.dueDate)}</small></span></div></div></article><article class="panel"><div class="panel-header"><div><h2>Enlaces importantes</h2></div></div><div class="panel-body"><div class="toolbar"><button class="button button-secondary">${icon('folder')} Drive</button><button class="button button-secondary">${icon('external')} GitHub</button><button class="button button-secondary">${icon('layers')} Figma</button></div></div></article></div>`;
}
